In [5]:
from azureml import Workspace
ws = Workspace()
experiment = ws.experiments['42f3ccc74a8a4a9eb6edb1ffecb985ec.f-id.140053a4a08e426ba8e558364b5cfdf3']
ds = experiment.get_intermediate_dataset(
    node_id='e042aa8a-4c36-4bd5-98a1-2084b0db2ad6-1919',
    port_name='Results dataset',
    data_type_id='GenericCSV'
)
frame = ds.to_dataframe()

In [6]:
frame

,User,Item 1,Item 2,Item 3,Item 4,Item 5
0,07caa920795cd4f20bfeeb0e192a5ddd9566ecdd,a054P00000uaFgL,a054P00000uaFhE,a054P00000uaFg6,a054P00000uaFdS,a054P00000uaFjF
1,f927dddfe26b0c74ada3eaadca41bfb462c37ee4,a054P00000uaFZv,a054P00000uaFiR,a054P00000uaFg6,a054P00000uaFdS,a054P00000uaFap
2,c737ec8c1b16ce8e39115f4432c9a7fc21ec47a1,a054P00000uaFXG,a054P00000uaFeg,a054P00000uaFRw,a054P00000uaFhZ,NaN
3,ff4322e94814d3c7895d07e6f94139b092862611,a054P00000uaFak,a054P00000uaFTU,a054P00000uaFl6,a054P00000uaFZ3,NaN
4,b64cdd1a0bd907e5e00b39e345194768e330d652,a054P00000uaFUI,a054P00000uaFjA,NaN,NaN,NaN
5,d6589314c0a9bcbca4fee0c93b14bc402363afea,a054P00000uaFhT,a054P00000uaFl6,a054P00000uaFYe,a054P00000uaFca,a054P00000uaFZC
6,c231bc806c239b1322421e66fc001822a9b2c2f0,a054P00000uaFkS,a054P00000uaFXa,a054P00000uaFZa,a054P00000uaFYe,a054P00000uaFg8
7,fca15b7964a099b2860dfdb158a2430fb10c4384,a054P00000uaFZQ,a054P00000uaFh1,NaN,NaN,NaN

In [30]:
SongIDs=[]
Map= {}

for index, row in  frame.iterrows():
    for i in range(1,6) :
        SongID1=[]
        SongID1.append(row['User'])
        SongID1.append(row['Item '+str(i)])
        SongIDs.append(SongID1)
#     SongID.append(row['Item 1'])
#     SongID.append(row['Item 2'])
#     SongID.append(row['Item 3'])
#     SongID.append(row['Item 4'])
#     SongID.append(row['Item 5'])
#     Map[index]=row['Item 1']
#     print(index, row['Item 1'], row['Item 2'], row['Item 3'])
    
result = pd.DataFrame(SongIDs, columns = ['userID', 'SongID']) 
result.head(5)

                                     userID           SongID
0  07caa920795cd4f20bfeeb0e192a5ddd9566ecdd  a054P00000uaFgL
1  07caa920795cd4f20bfeeb0e192a5ddd9566ecdd  a054P00000uaFhE
2  07caa920795cd4f20bfeeb0e192a5ddd9566ecdd  a054P00000uaFg6
3  07caa920795cd4f20bfeeb0e192a5ddd9566ecdd  a054P00000uaFdS
4  07caa920795cd4f20bfeeb0e192a5ddd9566ecdd  a054P00000uaFjF

In [35]:
url = 'https://raw.githubusercontent.com/suhasbalanagar/Digital-Marketing-and-Analytics/master/CustomerDataVeryFinall.csv'
namedf = pd.read_csv(url)
namedf.head(2)

,userID,Name,Created Year,Created Time,Profit/User,CAC,CLV,StateID,Subscription,Genre ID,Usage,CustomerType,Last Login Date,Email,Age,Payment Method,Current Occupation,Product Rating,Listening Time,Customer Rating
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Ankita Brahmankar,2011,12:07,2075.009,32,20718.09,6,6 month subscription,3,Windows,Existing,07/20/2012,alissandri18@businesswire.com,30,bankcard,Other,Neutral,Night,4
1,bd4c6e843f00bd476847fb75c47b4fb430a06856,Anuja Suryawanshi,2018,12:18,7617.625,32,76144.25,33,Free users subscription,7,MAC,Existing,03/02/2018,aschowenburg1@shareasale.com,62,jcb,Home maker,Neutral,Morning,2

In [39]:
#Merge the two dataframes above to create input dataframe for recommender systems
result_df = pd.merge(result, namedf, on="userID", how = 'inner')

In [46]:
result_df.head(3)

,userID,SongID,Name,Created Year,Created Time,Profit/User,CAC,CLV,StateID,Subscription,...,Usage,CustomerType,Last Login Date,Email,Age,Payment Method,Current Occupation,Product Rating,Listening Time,Customer Rating
0,07caa920795cd4f20bfeeb0e192a5ddd9566ecdd,a054P00000uaFgL,Akash Indani,2010,8:10,8871.55,32,88683.5,34,3 month subscription,...,Android,Existing,04/07/2010,swinsom1e@vistaprint.com,34,visa-electron,Unemployed,Dissatisfied,Afternoon,3
1,07caa920795cd4f20bfeeb0e192a5ddd9566ecdd,a054P00000uaFhE,Akash Indani,2010,8:10,8871.55,32,88683.5,34,3 month subscription,...,Android,Existing,04/07/2010,swinsom1e@vistaprint.com,34,visa-electron,Unemployed,Dissatisfied,Afternoon,3
2,07caa920795cd4f20bfeeb0e192a5ddd9566ecdd,a054P00000uaFg6,Akash Indani,2010,8:10,8871.55,32,88683.5,34,3 month subscription,...,Android,Existing,04/07/2010,swinsom1e@vistaprint.com,34,visa-electron,Unemployed,Dissatisfied,Afternoon,3

In [7]:
%%capture
!pip3 install gspread oauth2client df2gspread

In [8]:
#%%capture
!conda install -c conda-forge df2gspread

Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - df2gspread -> python 2.7* -> libgcc-ng >=4.9
  - df2gspread -> python 2.7* -> libstdcxx-ng >=4.9
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package.

In [9]:
import pyasn1
import pyasn1_modules

In [10]:

#!conda install Pyrebase --yes

In [11]:
#!conda install google-auth-oauthlib --yes

In [12]:
#%%capture
#!conda uninstall pyasn1 --yes

In [13]:
#!pip3 uninstall pyasn1 --y

In [14]:
%%%capture
!conda install pyasn1-modules --yes

In [15]:
pyasn1.__version__

'0.1.7'

In [16]:
# Import libraries 
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
# For connect to google sheet
#import gspread
#from df2gspread import df2gspread as d2g

In [17]:
import gspread
from df2gspread import df2gspread as d2g

In [18]:
from oauth2client.service_account import ServiceAccountCredentials

In [41]:
from IPython.display import HTML
import random

def hide_toggle(for_next=False):
    this_cell = """$('div.cell.code_cell.rendered.selected')"""
    next_cell = this_cell + '.next()'

    toggle_text = 'Toggle show/hide'  # text shown on toggle link
    target_cell = this_cell  # target cell to control with toggle
    js_hide_current = ''  # bit of JS to permanently hide code in current cell (only when toggling next cell)

    if for_next:
        target_cell = next_cell
        toggle_text += ' next cell'
        js_hide_current = this_cell + '.find("div.input").hide();'

    js_f_name = 'code_toggle_{}'.format(str(random.randint(1,2**64)))

    html = """
        <script>
            function {f_name}() {{
                {cell_selector}.find('div.input').toggle();
            }}

            {js_hide_current}
        </script>

        <a href="javascript:{f_name}()">{toggle_text}</a>
    """.format(
        f_name=js_f_name,
        cell_selector=target_cell,
        js_hide_current=js_hide_current, 
        toggle_text=toggle_text
    )

    return HTML(html)

hide_toggle()

In [43]:

service_account=dict()
service_account["type"]= "service_account"
service_account["project_id"]="hardy-tine-249610"
service_account["private_key_id"]= "e54069e1642af5fbbb3249528601f3fae6e4f841"
service_account["private_key"]= "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDX9eiA4Wx67/8e\nUKnIo9ssNxeG69X+btMflKkNgRHkISW+K2C72q0yLfBOq3tu1xRfdMU4umGiWuJI\nBKFDckGCB7NlyaHcvQYKMd8VCQ9eHxAWOHpIthVY+XEQg85OzJhL9FvcrHajmnma\nwRAFb8NMtY1GUGp9fO2qfw2jeopSuCkSmNyhyqIgNFHXEfrsTRhkyyuavDygWoFM\nPWez9D8Y9o0M/7tbolrGxTDu0P5MY94ITelUMiIKG8oj2w05id3GDd2g9sFloAfa\n1jr20upZqKcZ+kNBETiwTDs0WwV+NudfOex8lFTyRX31JWiSlfBAyhSM+ZhG6v3U\nSpmRBzj9AgMBAAECggEAOcVHHp7u8Y4c/YOPf6RRn6jXKtkQxEDqSlLuzDWATzoM\nyiv5cxdC6J8AX1MhMFvpz8VBcvTs5E0SpjhS2WOJoZqkw3BmU9He+UAxEIP9b+y4\nVXFjSOsol8YWmFfiCxNRFFR4dHZQQGC08hB+VC37HRyd/7bIXexa+ZaGU/qWYRzz\n1lTujCdyxV2oa/VMHkM/BQYLDg2Ztgd/BKHBxTJawzNcsPBIXCvuHwPQr1OhTLpy\nZ6OLp9L21TcjsEA311ktmJd4LvdJu6gLvS0faeBrgQzTCuh1HYptRl5UjQmpZo/N\naEG2S3Nu1U8giL7UX3DLjGibBKnqW4oQznQ7FjCa8wKBgQDs+kfpP4W6y+GQW8fx\n5DhJbvbTKmvkJLKBHpjbMdVPhbP8s2Lis1uf05/iVlQQ36DAzl4ZLdenjwo3XdVt\n0YFL6LX0Kbk1hiHZbdvtULLiuB1ucOVhS/ljuSq9N2T3rRKXTcvi9inWjTpiT1j4\nWbZc4b6j/fXmeBYmDhckgHK4rwKBgQDpS73VnagethYsiztQp6g1BN5xGb/NENhE\nktNHEVpUzCfwLFTUrcqt+Bqotit7OPE9qCBYxyyJj/Fpx3nr11E1rStklB/ItPtH\n2jKUR7sm0muRy/doV58Uuq7hRWDKUIs5C/Wj/jPZCstmh7DPIhHFbMh/HtkR9vPL\nb1xUGA28EwKBgAr2qU0JO06hEBZ1qJJwVIpRL+olFEjByeBfYgMCEzRSozkVs4V5\ndsu2Jrd59vmw3ucMpR3VGR0PaRGWrcEe6DRy17gsFf177yT4CCy6hwwmKHZrkrEl\nqqwKbQfEAE/VGf8WAlDFwrnCXukdcqhKvj0d1IwRu8al16B7FmcB6kzRAoGABwUU\nbT0VNfdcq3J1EnQ5B39iAh04PD9pgoa4fMb05OBPw1ZSJyQjmSCCDNmObWLFP4mz\nj3hOysTeCsTJ0mLkOq0/RQOAAVYQyZSzOOr/oqdqPTTZ+PXJ/6GuaXDg/LV3uvu1\nJH4dqUY94JPsqg7oYfxn/As9lODNbS2opY8juqkCgYAzNti28T3XT9vxMg6TFD+a\nBNZUyoN4a0FH85VlAS9Xi7clsKRxd8c2zAVi3vKHoGsBowaY8g1Siw6pWok3hkeV\npj6nQJ974A16lnShyFIFRZyYkS8ZGDLhb9nAWmz5n0+VmbkdYvI7jHfULwXTrjzG\nlap4EpBrjXhtMobMjDb1vQ==\n-----END PRIVATE KEY-----\n"
service_account["client_email"]= "google-sheet@hardy-tine-249610.iam.gserviceaccount.com"
service_account["client_id"]= "101398093074194559131"
service_account["auth_uri"]="https://accounts.google.com/o/oauth2/auth"
service_account["token_uri"]= "https://oauth2.googleapis.com/token"
service_account["auth_provider_x509_cert_url"]= "https://www.googleapis.com/oauth2/v1/certs"
service_account["client_x509_cert_url"]= "https://www.googleapis.com/robot/v1/metadata/x509/google-sheet%40hardy-tine-249610.iam.gserviceaccount.com"
hide_toggle()

In [44]:

# Configure the connection 
scope = ['https://spreadsheets.google.com/feeds']

# Give the path to the Service Account Credential json file 
credentials = ServiceAccountCredentials.from_json_keyfile_dict(service_account,scope)
# Authorise your Notebook
gc = gspread.authorize(credentials)

# The sprad sheet ID, which can be taken from the link to the sheet
spreadsheet_key = '1Uk8dy8NWHyrzuEDqYtbEDRWa281uuorofnY8w67QQew'

In [47]:
# Set the sheet name you want to upload data to and the start cell where the upload data begins 
wks_name = 'Sheet1'
cell_of_start_df = 'A2'
# upload the dataframe of the clients we want to delete
d2g.upload(result_df,
           spreadsheet_key,
           wks_name,
           credentials=credentials,
           col_names=False,
           row_names=False,
           start_cell = cell_of_start_df,
           clean=False)
print ('The sheet is updated successfully')

The sheet is updated successfully